# Generated by Django 2.2.9 on 2020-01-06 16:22

from django.db import migrations, models
import django.db.models.deletion
import partial_date.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='timelineevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', partial_date.fields.PartialDateField()),
                ('is_bc', models.BooleanField(default=False)),
                ('location', models.TextField(null=True)),
                ('comment', models.TextField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.books')),
            ],
        ),
    ]
