# Generated by Django 3.0.3 on 2020-04-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='precision',
            field=models.CharField(choices=[('YR', 'Jahr'), ('EX', 'Tag od Monat'), ('YA', 'ca Jahr'), ('DA', 'ca Jahrzehnt'), ('CA', 'ca Jahrhundert'), ('G?', 'vermutlich'), ('FN', 'nahe Zukunft'), ('FF', 'ferne Zukunft'), ('FU', 'Zukunft'), ('ND', 'unbestimmt'), ('UN', 'unbekannt od nicht datierbar')], default='ND', max_length=2),
        ),
    ]
