# Generated by Django 2.0.13 on 2019-09-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='is_bc',
            field=models.BooleanField(default=False),
        ),
    ]
