# Generated by Django 4.0 on 2021-12-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_timelineevent_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
