# Generated by Django 2.0.9 on 2018-12-13 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='linksites_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='author_links',
            old_name='link_target',
            new_name='link_site',
        ),
        migrations.RenameField(
            model_name='book_links',
            old_name='link_target',
            new_name='link_site',
        ),
        migrations.RenameModel(
            old_name='linktargets',
            new_name='linksites',
        ),
        migrations.AddField(
            model_name='linksites_url',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='bookmarks.linksites'),
        ),
    ]
