# Generated by Django 2.2.9 on 2020-01-06 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('lowerCaseName', models.TextField()),
                ('familyName', models.TextField()),
                ('updated', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn10', models.TextField(max_length=10, null=True)),
                ('isbn13', models.TextField(max_length=13, null=True)),
                ('title', models.TextField(max_length=255)),
                ('binding', models.CharField(max_length=80, null=True)),
                ('orig_description', models.TextField(blank=True, null=True)),
                ('new_description', models.TextField(blank=True, null=True)),
                ('numberOfPages', models.CharField(blank=True, max_length=10, null=True)),
                ('publisher', models.TextField(blank=True, null=True)),
                ('publicationDate', models.DateField(null=True)),
                ('reviewsFetchedDate', models.DateField(null=True)),
                ('offersFetchedDate', models.DateField(null=True)),
                ('grRating', models.FloatField(null=True)),
                ('grRatingsCount', models.IntegerField(null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('created', models.DateField()),
                ('updated', models.DateField(null=True)),
                ('userRating', models.IntegerField(null=True)),
                ('lentToName', models.CharField(max_length=120, null=True)),
                ('lentToUri', models.TextField(blank=True, null=True)),
                ('thumbnailSmall', models.TextField(blank=True, null=True)),
                ('thumbnailLarge', models.TextField(blank=True, null=True)),
                ('amazonBookId', models.IntegerField(null=True)),
                ('authors', models.ManyToManyField(to='bookshelf.authors')),
            ],
            options={
                'permissions': (('can_create', 'Create book'), ('can_edit', 'Edit book'), ('can_delete', 'Delete book')),
            },
        ),
        migrations.CreateModel(
            name='groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='states',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
                ('haveRead', models.BooleanField(default=False)),
                ('readingNow', models.BooleanField(default=False)),
                ('iOwn', models.BooleanField(default=False)),
                ('toBuy', models.BooleanField(default=False)),
                ('toRead', models.BooleanField(default=False)),
                ('book', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookshelf.books')),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grReviewId', models.TextField()),
                ('dateCreated', models.IntegerField()),
                ('userName', models.TextField()),
                ('userUrl', models.TextField()),
                ('url', models.TextField()),
                ('body', models.TextField()),
                ('fullBody', models.TextField()),
                ('rating', models.IntegerField()),
                ('votes', models.IntegerField()),
                ('spoiler', models.TextField()),
                ('book', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookshelf.books')),
            ],
        ),
        migrations.CreateModel(
            name='onleiheBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onleiheId', models.TextField(null=True)),
                ('status', models.TextField()),
                ('bookCoverURL', models.TextField(null=True)),
                ('author', models.TextField(null=True)),
                ('translator', models.TextField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('isbn', models.TextField(max_length=13, null=True)),
                ('category', models.TextField(null=True)),
                ('keywords', models.TextField(null=True)),
                ('publisher', models.TextField(null=True)),
                ('format', models.TextField(null=True)),
                ('pages', models.IntegerField(null=True)),
                ('allow_copy', models.NullBooleanField()),
                ('book_description', models.TextField(null=True)),
                ('updated', models.DateField(null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.books')),
            ],
        ),
        migrations.CreateModel(
            name='grBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grId', models.TextField(null=True)),
                ('grAvgRating', models.FloatField(null=True)),
                ('grRatingsCount', models.IntegerField(null=True)),
                ('grRatingsSum', models.IntegerField(null=True)),
                ('grRatingDistOne', models.IntegerField(null=True)),
                ('grRatingDistTwo', models.IntegerField(null=True)),
                ('grRatingDistThree', models.IntegerField(null=True)),
                ('grRatingDistFour', models.IntegerField(null=True)),
                ('grRatingDistFive', models.IntegerField(null=True)),
                ('grLinkDetail', models.TextField(null=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grBookId', to='bookshelf.books')),
            ],
        ),
        migrations.CreateModel(
            name='googleBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField()),
                ('subtitle', models.TextField(null=True)),
                ('subject', models.TextField(null=True)),
                ('publisher', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('format', models.TextField(null=True)),
                ('googleLink', models.TextField(null=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='googleBookId', to='bookshelf.books')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('bookTitle', models.TextField()),
                ('dateCreatedInt', models.IntegerField(null=True)),
                ('dateCreated', models.DateTimeField()),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookshelf.books')),
            ],
            options={
                'ordering': ['-dateCreated'],
            },
        ),
        migrations.AddIndex(
            model_name='authors',
            index=models.Index(fields=['name'], name='author_name'),
        ),
    ]
