# Generated by Django 2.2.9 on 2020-01-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='dateCreatedInt',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='dateCreated',
            field=models.BigIntegerField(),
        ),
    ]
