# Generated by Django 2.0.3 on 2018-03-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='authors',
            index=models.Index(fields=['name'], name='author_name'),
        ),
    ]
