# Generated by Django 3.0.3 on 2020-04-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_auto_20200106_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='short_bio',
            field=models.TextField(null=True),
        ),
    ]
