# Generated by Django 3.0.3 on 2020-04-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_authors_short_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='unified_title',
            field=models.TextField(null=True),
        ),
    ]
