# Generated by Django 2.0.3 on 2018-04-03 08:59

from django.db import migrations, models

def set_dateCreatedInt(apps, schema_editor):
    comments = apps.get_model("bookshelf", "comments")
    db_alias = schema_editor.connection.alias
    for comment in comments.objects.using(db_alias).all():
        comment.dateCreatedInt = comment.dateCreated
        comment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_auto_20180331_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='stateId',
        ),
        migrations.AddField(
            model_name='comments',
            name='dateCreatedInt',
            field=models.IntegerField(null=True),
        ),
        # migrations.AlterField ?
        #migrations.RunSQL("UPDATE bookshelf_comment SET dateCreatedInt = dateCreated", reverse_sql=None)
        migrations.RunPython(set_dateCreatedInt)
    ]
