# Generated by Django 3.0.3 on 2020-04-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0004_books_unified_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_serie',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
