# Generated by Django 2.0.3 on 2018-04-03 09:20

from django.db import migrations, models
from datetime import datetime


def update_dateCreated(apps, schema_editor):
    # ATTN ignoring RuntimeWarning: DateTimeField comments.dateCreated received a naive datetime (...) while time zone support is active.
    # assume configured timezone is appropriate
    comments = apps.get_model("bookshelf", "comments")
    db_alias = schema_editor.connection.alias
    for comment in comments.objects.using(db_alias).all():
        ts = comment.dateCreatedInt
        comment.dateCreated = datetime.fromtimestamp(ts/1000.0)
        comment.save()



class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0004_auto_20180403_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='dateCreated',
            field=models.DateTimeField(),
        ),
        migrations.RunPython(update_dateCreated),
    ]
