# Generated by Django 3.0.3 on 2020-05-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0005_books_book_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
