# Generated by Django 3.0.3 on 2020-05-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0006_states_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='obsolete',
            field=models.BooleanField(default=False),
        ),
    ]
