# Generated by Django 3.0.3 on 2020-05-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0007_states_obsolete'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='obsolete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='books',
            name='sync_mybookdroid',
            field=models.DateField(null=True),
        ),
    ]
