# Generated by Django 2.0.8 on 2018-08-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0007_books_new_description'),
    ]

    operations = [
        #migrations.AddField(
            #model_name='books',
            #name='orig_description',
            #field=models.TextField(blank=True, null=True),
        #),
        #migrations.RemoveField(
            #model_name='books',
            #name='description',
        #),
        migrations.RenameField(
            model_name='books',
            old_name='description',
            new_name='orig_description',
        ),
    ]
