# Generated by Django 3.0.6 on 2020-06-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0008_auto_20200521_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='onleihebooks',
            name='length',
            field=models.TextField(null=True),
        ),
    ]
