# Generated by Django 2.0.9 on 2018-10-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0008_books_orig_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='states',
            name='haveRead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='states',
            name='iOwn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='states',
            name='readingNow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='states',
            name='toBuy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='states',
            name='toRead',
            field=models.BooleanField(default=False),
        ),
    ]
