# Generated by Django 2.0.9 on 2018-11-18 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0009_auto_20181031_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='onleiheBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onleiheId', models.TextField()),
                ('status', models.TextField()),
                ('bookCoverURL', models.TextField(null=True)),
                ('year', models.IntegerField()),
                ('isbn', models.TextField(max_length=13)),
                ('imgCoverURL', models.TextField()),
                ('publisher', models.TextField()),
                ('format', models.TextField()),
                ('pages', models.IntegerField()),
                ('allow_copy', models.BooleanField()),
                ('book_description', models.TextField()),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.books')),
            ],
        ),
    ]
