# Generated by Django 2.0.9 on 2018-11-18 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0010_onleihebooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onleihebooks',
            name='imgCoverURL',
        ),
    ]
