# Generated by Django 3.0.6 on 2020-06-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0010_books_bookcatalogueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='language',
            field=models.TextField(max_length='2', null=True),
        ),
        migrations.AddField(
            model_name='onleihebooks',
            name='language',
            field=models.TextField(null=True),
        ),
    ]
