# Generated by Django 3.0.7 on 2020-06-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0011_auto_20200605_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='read_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='read_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
