# Generated by Django 2.0.9 on 2018-11-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0011_remove_onleihebooks_imgcoverurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='onleihebooks',
            name='updated',
            field=models.DateField(null=True),
        ),
    ]
