# Generated by Django 2.0.9 on 2018-11-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0012_onleihebooks_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='onleihebooks',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
