# Generated by Django 3.0.7 on 2020-08-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0012_auto_20200607_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='userRating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
