# Generated by Django 2.0.9 on 2018-11-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0013_onleihebooks_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='onleihebooks',
            name='author',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='onleihebooks',
            name='category',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='onleihebooks',
            name='keywords',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='onleihebooks',
            name='translator',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='onleihebooks',
            name='allow_copy',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='onleihebooks',
            name='book_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='onleihebooks',
            name='format',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='onleihebooks',
            name='isbn',
            field=models.TextField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='onleihebooks',
            name='onleiheId',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='onleihebooks',
            name='pages',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='onleihebooks',
            name='publisher',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='onleihebooks',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
