# Generated by Django 3.1.5 on 2021-01-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0014_books_synced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onleihebooks',
            name='allow_copy',
            field=models.BooleanField(null=True),
        ),
    ]
